server:
  port: 8080

spring:
  application:
    name: back

  profiles:
    active: dev

  jackson:
    serialization:
      fail-on-empty-beans: false

  kafka:
    # ðŸ”‘ Redpanda / Kafka ë¸Œë¡œì»¤ ì£¼ì†Œ
    bootstrap-servers: localhost:19092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    consumer:
      group-id: back
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.back.*"
        spring.json.use.type.headers: true

logging:
  level:
    com.back: DEBUG
